### ISSUE TITLE
Prisma migrations

### ISSUE THREAD

**Issue by mderome** [ethan0905/ft_transcendance#3]
problem with prisma's migration

**Comment by ethan0905** [comment]
have also some trouble with prisma schema. 
in my case I have ambiguous relation detected inside my models
```
model Message {
 [...]
  senderId  Int
  sender    User @relation(fields: [senderId], references: [id])

  receiverId  Int
  receiver    User @relation(fields: [receiverId], references: [id])
 [...]
}
```
gonna look further to debug:
https://github.com/prisma/prisma/issues/633

**Comment by ethan0905** [comment]
interesting article to fix prisma migrations: https://notiz.dev/blog/prisma-migrate-deploy-with-docker

**Comment by ethan0905** [comment]
Prisma migration fixed, you can follow the Readme instructions.
